# Configure a Sponsors button on the repo page when ready.
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [Mr-DS-ML-85]
# ko_fi: your-username
# custom: ["https://your-site.example/donate"]
